[package]
name = "kanens-lovely-format"
version = "0.2.1"
entrypoint = "lib.typ"
authors = ["Kanen Stephens"]
license = "MIT"
description = "Kanen's Lovely Format -- A lovely essay format by Kanen Stephens :D"
